/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FilterOption, MealSlotRecipe, RatingBadgeVariant, RecipeFormErrors, RecipeFormValue } from "./types";
export { FilterOption, MealSlotRecipe, RatingBadgeVariant, RecipeFormErrors, RecipeFormValue } from "./types";
export namespace Components {
    /**
     * A recipe summary card — used across the discovery grid, favorites list, and
     * the meal-plan recipe picker. Purely presentational: it never fetches data
     * or reads app state, only emits events for the host app to act on.
     */
    interface RecipeUiCard {
        "category"?: string;
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Identifies the recipe in emitted events; not rendered.
         */
        "recipeId": string;
        /**
          * Recipe name. Named `recipeTitle` (not `title`) to avoid colliding with the native HTML `title` tooltip attribute.
         */
        "recipeTitle": string;
    }
    /**
     * A row of toggleable filter chips (e.g. recipe categories or cuisines).
     * Multi-select: clicking a chip emits the full next `selected` array and
     * waits for the host app to feed it back via the `selected` prop — the
     * component does not keep its own copy of selection state.
     */
    interface RecipeUiFilterChipGroup {
        /**
          * @default []
         */
        "options": FilterOption[];
        /**
          * @default []
         */
        "selected": string[];
    }
    /**
     * Collects a recipe (title, image, category, ingredients, instructions) and
     * emits it on submit. Deliberately has no built-in business validation
     * beyond marking fields as `required` for baseline UX — the host app
     * validates and feeds errors back in via the `errors` prop, per the
     * Recipe Management requirement ("validate recipe input before saving").
     */
    interface RecipeUiForm {
        /**
          * Field-level errors from the host app's validation, keyed by field name.
         */
        "errors"?: RecipeFormErrors;
        "initialValue"?: RecipeFormValue;
        /**
          * @default 'create'
         */
        "mode": 'create' | 'edit';
    }
    /**
     * One day's cell in the weekly meal-plan grid: either an "add recipe" prompt or the assigned recipe with a remove control.
     */
    interface RecipeUiMealSlot {
        /**
          * Weekday key, e.g. "mon" — passed back unchanged in emitted events.
          * @default ''
         */
        "day": string;
        /**
          * Optional display label; falls back to `day` if omitted.
         */
        "dayLabel"?: string;
        /**
          * @default null
         */
        "recipe": MealSlotRecipe | null;
    }
    /**
     * A generic modal shell. Used as the meal-plan recipe picker: the host app
     * puts a `<recipe-ui-card>` grid in the default slot and, optionally, action
     * buttons in the `footer` slot.
     */
    interface RecipeUiModalDialog {
        "heading"?: string;
        /**
          * @default false
         */
        "open": boolean;
    }
    /**
     * A small colored label — e.g. a difficulty/cuisine/dietary tag on a recipe details page.
     */
    interface RecipeUiRatingBadge {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'neutral'
         */
        "variant": RatingBadgeVariant;
    }
    /**
     * A debounced search input. Owns only keystroke-to-debounced-event plumbing;
     * it never calls an API itself — the host app listens for `searchChange` and
     * decides what to do with the value.
     */
    interface RecipeUiSearchBar {
        /**
          * @default 300
         */
        "debounceMs": number;
        /**
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface RecipeUiCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiCardElement;
}
export interface RecipeUiFilterChipGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiFilterChipGroupElement;
}
export interface RecipeUiFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiFormElement;
}
export interface RecipeUiMealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiMealSlotElement;
}
export interface RecipeUiModalDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiModalDialogElement;
}
export interface RecipeUiSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeUiSearchBarElement;
}
declare global {
    interface HTMLRecipeUiCardElementEventMap {
        "cardClick": { recipeId: string };
        "favoriteToggle": { recipeId: string };
    }
    /**
     * A recipe summary card — used across the discovery grid, favorites list, and
     * the meal-plan recipe picker. Purely presentational: it never fetches data
     * or reads app state, only emits events for the host app to act on.
     */
    interface HTMLRecipeUiCardElement extends Components.RecipeUiCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiCardElementEventMap>(type: K, listener: (this: HTMLRecipeUiCardElement, ev: RecipeUiCardCustomEvent<HTMLRecipeUiCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiCardElementEventMap>(type: K, listener: (this: HTMLRecipeUiCardElement, ev: RecipeUiCardCustomEvent<HTMLRecipeUiCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiCardElement: {
        prototype: HTMLRecipeUiCardElement;
        new (): HTMLRecipeUiCardElement;
    };
    interface HTMLRecipeUiFilterChipGroupElementEventMap {
        "filterChange": { selected: string[] };
    }
    /**
     * A row of toggleable filter chips (e.g. recipe categories or cuisines).
     * Multi-select: clicking a chip emits the full next `selected` array and
     * waits for the host app to feed it back via the `selected` prop — the
     * component does not keep its own copy of selection state.
     */
    interface HTMLRecipeUiFilterChipGroupElement extends Components.RecipeUiFilterChipGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiFilterChipGroupElementEventMap>(type: K, listener: (this: HTMLRecipeUiFilterChipGroupElement, ev: RecipeUiFilterChipGroupCustomEvent<HTMLRecipeUiFilterChipGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiFilterChipGroupElementEventMap>(type: K, listener: (this: HTMLRecipeUiFilterChipGroupElement, ev: RecipeUiFilterChipGroupCustomEvent<HTMLRecipeUiFilterChipGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiFilterChipGroupElement: {
        prototype: HTMLRecipeUiFilterChipGroupElement;
        new (): HTMLRecipeUiFilterChipGroupElement;
    };
    interface HTMLRecipeUiFormElementEventMap {
        "formSubmit": { recipe: RecipeFormValue };
        "cancel": void;
    }
    /**
     * Collects a recipe (title, image, category, ingredients, instructions) and
     * emits it on submit. Deliberately has no built-in business validation
     * beyond marking fields as `required` for baseline UX — the host app
     * validates and feeds errors back in via the `errors` prop, per the
     * Recipe Management requirement ("validate recipe input before saving").
     */
    interface HTMLRecipeUiFormElement extends Components.RecipeUiForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiFormElementEventMap>(type: K, listener: (this: HTMLRecipeUiFormElement, ev: RecipeUiFormCustomEvent<HTMLRecipeUiFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiFormElementEventMap>(type: K, listener: (this: HTMLRecipeUiFormElement, ev: RecipeUiFormCustomEvent<HTMLRecipeUiFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiFormElement: {
        prototype: HTMLRecipeUiFormElement;
        new (): HTMLRecipeUiFormElement;
    };
    interface HTMLRecipeUiMealSlotElementEventMap {
        "assign": { day: string };
        "remove": { day: string };
    }
    /**
     * One day's cell in the weekly meal-plan grid: either an "add recipe" prompt or the assigned recipe with a remove control.
     */
    interface HTMLRecipeUiMealSlotElement extends Components.RecipeUiMealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiMealSlotElementEventMap>(type: K, listener: (this: HTMLRecipeUiMealSlotElement, ev: RecipeUiMealSlotCustomEvent<HTMLRecipeUiMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiMealSlotElementEventMap>(type: K, listener: (this: HTMLRecipeUiMealSlotElement, ev: RecipeUiMealSlotCustomEvent<HTMLRecipeUiMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiMealSlotElement: {
        prototype: HTMLRecipeUiMealSlotElement;
        new (): HTMLRecipeUiMealSlotElement;
    };
    interface HTMLRecipeUiModalDialogElementEventMap {
        "close": void;
    }
    /**
     * A generic modal shell. Used as the meal-plan recipe picker: the host app
     * puts a `<recipe-ui-card>` grid in the default slot and, optionally, action
     * buttons in the `footer` slot.
     */
    interface HTMLRecipeUiModalDialogElement extends Components.RecipeUiModalDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiModalDialogElementEventMap>(type: K, listener: (this: HTMLRecipeUiModalDialogElement, ev: RecipeUiModalDialogCustomEvent<HTMLRecipeUiModalDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiModalDialogElementEventMap>(type: K, listener: (this: HTMLRecipeUiModalDialogElement, ev: RecipeUiModalDialogCustomEvent<HTMLRecipeUiModalDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiModalDialogElement: {
        prototype: HTMLRecipeUiModalDialogElement;
        new (): HTMLRecipeUiModalDialogElement;
    };
    /**
     * A small colored label — e.g. a difficulty/cuisine/dietary tag on a recipe details page.
     */
    interface HTMLRecipeUiRatingBadgeElement extends Components.RecipeUiRatingBadge, HTMLStencilElement {
    }
    var HTMLRecipeUiRatingBadgeElement: {
        prototype: HTMLRecipeUiRatingBadgeElement;
        new (): HTMLRecipeUiRatingBadgeElement;
    };
    interface HTMLRecipeUiSearchBarElementEventMap {
        "searchChange": { value: string };
    }
    /**
     * A debounced search input. Owns only keystroke-to-debounced-event plumbing;
     * it never calls an API itself — the host app listens for `searchChange` and
     * decides what to do with the value.
     */
    interface HTMLRecipeUiSearchBarElement extends Components.RecipeUiSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeUiSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeUiSearchBarElement, ev: RecipeUiSearchBarCustomEvent<HTMLRecipeUiSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeUiSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeUiSearchBarElement, ev: RecipeUiSearchBarCustomEvent<HTMLRecipeUiSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeUiSearchBarElement: {
        prototype: HTMLRecipeUiSearchBarElement;
        new (): HTMLRecipeUiSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "recipe-ui-card": HTMLRecipeUiCardElement;
        "recipe-ui-filter-chip-group": HTMLRecipeUiFilterChipGroupElement;
        "recipe-ui-form": HTMLRecipeUiFormElement;
        "recipe-ui-meal-slot": HTMLRecipeUiMealSlotElement;
        "recipe-ui-modal-dialog": HTMLRecipeUiModalDialogElement;
        "recipe-ui-rating-badge": HTMLRecipeUiRatingBadgeElement;
        "recipe-ui-search-bar": HTMLRecipeUiSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * A recipe summary card — used across the discovery grid, favorites list, and
     * the meal-plan recipe picker. Purely presentational: it never fetches data
     * or reads app state, only emits events for the host app to act on.
     */
    interface RecipeUiCard {
        "category"?: string;
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Fired when the card body (not the favorite button) is clicked.
         */
        "onCardClick"?: (event: RecipeUiCardCustomEvent<{ recipeId: string }>) => void;
        /**
          * Fired when the favorite button is toggled.
         */
        "onFavoriteToggle"?: (event: RecipeUiCardCustomEvent<{ recipeId: string }>) => void;
        /**
          * Identifies the recipe in emitted events; not rendered.
         */
        "recipeId": string;
        /**
          * Recipe name. Named `recipeTitle` (not `title`) to avoid colliding with the native HTML `title` tooltip attribute.
         */
        "recipeTitle": string;
    }
    /**
     * A row of toggleable filter chips (e.g. recipe categories or cuisines).
     * Multi-select: clicking a chip emits the full next `selected` array and
     * waits for the host app to feed it back via the `selected` prop — the
     * component does not keep its own copy of selection state.
     */
    interface RecipeUiFilterChipGroup {
        /**
          * Named `filterChange`, not `selectionChange`, to avoid colliding with the native `selectionchange` DOM event.
         */
        "onFilterChange"?: (event: RecipeUiFilterChipGroupCustomEvent<{ selected: string[] }>) => void;
        /**
          * @default []
         */
        "options"?: FilterOption[];
        /**
          * @default []
         */
        "selected"?: string[];
    }
    /**
     * Collects a recipe (title, image, category, ingredients, instructions) and
     * emits it on submit. Deliberately has no built-in business validation
     * beyond marking fields as `required` for baseline UX — the host app
     * validates and feeds errors back in via the `errors` prop, per the
     * Recipe Management requirement ("validate recipe input before saving").
     */
    interface RecipeUiForm {
        /**
          * Field-level errors from the host app's validation, keyed by field name.
         */
        "errors"?: RecipeFormErrors;
        "initialValue"?: RecipeFormValue;
        /**
          * @default 'create'
         */
        "mode"?: 'create' | 'edit';
        "onCancel"?: (event: RecipeUiFormCustomEvent<void>) => void;
        /**
          * Named `formSubmit`, not `submit`, so it can't be confused with the native <form> submit event that bubbles inside this shadow root.
         */
        "onFormSubmit"?: (event: RecipeUiFormCustomEvent<{ recipe: RecipeFormValue }>) => void;
    }
    /**
     * One day's cell in the weekly meal-plan grid: either an "add recipe" prompt or the assigned recipe with a remove control.
     */
    interface RecipeUiMealSlot {
        /**
          * Weekday key, e.g. "mon" — passed back unchanged in emitted events.
          * @default ''
         */
        "day"?: string;
        /**
          * Optional display label; falls back to `day` if omitted.
         */
        "dayLabel"?: string;
        /**
          * Fired when the host app should open its recipe picker for this day — either because an empty slot was clicked, or because the "change" control on an already-filled slot was clicked. Assigning over a filled slot is how the "modify a planned meal" requirement is satisfied, so both paths emit the same event and the host app treats them identically.
         */
        "onAssign"?: (event: RecipeUiMealSlotCustomEvent<{ day: string }>) => void;
        /**
          * Fired when the remove control on a filled slot is clicked.
         */
        "onRemove"?: (event: RecipeUiMealSlotCustomEvent<{ day: string }>) => void;
        /**
          * @default null
         */
        "recipe"?: MealSlotRecipe | null;
    }
    /**
     * A generic modal shell. Used as the meal-plan recipe picker: the host app
     * puts a `<recipe-ui-card>` grid in the default slot and, optionally, action
     * buttons in the `footer` slot.
     */
    interface RecipeUiModalDialog {
        "heading"?: string;
        /**
          * Fired when the backdrop, close button, or Escape key requests the modal be closed. Host app owns the `open` prop and should flip it to false.
         */
        "onClose"?: (event: RecipeUiModalDialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * A small colored label — e.g. a difficulty/cuisine/dietary tag on a recipe details page.
     */
    interface RecipeUiRatingBadge {
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "variant"?: RatingBadgeVariant;
    }
    /**
     * A debounced search input. Owns only keystroke-to-debounced-event plumbing;
     * it never calls an API itself — the host app listens for `searchChange` and
     * decides what to do with the value.
     */
    interface RecipeUiSearchBar {
        /**
          * @default 300
         */
        "debounceMs"?: number;
        /**
          * Fired `debounceMs` after the user stops typing, with the current input value.
         */
        "onSearchChange"?: (event: RecipeUiSearchBarCustomEvent<{ value: string }>) => void;
        /**
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface RecipeUiCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "isFavorite": boolean;
    }
    interface RecipeUiFormAttributes {
        "mode": 'create' | 'edit';
    }
    interface RecipeUiMealSlotAttributes {
        "day": string;
        "dayLabel": string;
    }
    interface RecipeUiModalDialogAttributes {
        "open": boolean;
        "heading": string;
    }
    interface RecipeUiRatingBadgeAttributes {
        "label": string;
        "variant": RatingBadgeVariant;
    }
    interface RecipeUiSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "debounceMs": number;
    }

    interface IntrinsicElements {
        "recipe-ui-card": Omit<RecipeUiCard, keyof RecipeUiCardAttributes> & { [K in keyof RecipeUiCard & keyof RecipeUiCardAttributes]?: RecipeUiCard[K] } & { [K in keyof RecipeUiCard & keyof RecipeUiCardAttributes as `attr:${K}`]?: RecipeUiCardAttributes[K] } & { [K in keyof RecipeUiCard & keyof RecipeUiCardAttributes as `prop:${K}`]?: RecipeUiCard[K] } & OneOf<"recipeId", RecipeUiCard["recipeId"], RecipeUiCardAttributes["recipeId"]> & OneOf<"recipeTitle", RecipeUiCard["recipeTitle"], RecipeUiCardAttributes["recipeTitle"]>;
        "recipe-ui-filter-chip-group": RecipeUiFilterChipGroup;
        "recipe-ui-form": Omit<RecipeUiForm, keyof RecipeUiFormAttributes> & { [K in keyof RecipeUiForm & keyof RecipeUiFormAttributes]?: RecipeUiForm[K] } & { [K in keyof RecipeUiForm & keyof RecipeUiFormAttributes as `attr:${K}`]?: RecipeUiFormAttributes[K] } & { [K in keyof RecipeUiForm & keyof RecipeUiFormAttributes as `prop:${K}`]?: RecipeUiForm[K] };
        "recipe-ui-meal-slot": Omit<RecipeUiMealSlot, keyof RecipeUiMealSlotAttributes> & { [K in keyof RecipeUiMealSlot & keyof RecipeUiMealSlotAttributes]?: RecipeUiMealSlot[K] } & { [K in keyof RecipeUiMealSlot & keyof RecipeUiMealSlotAttributes as `attr:${K}`]?: RecipeUiMealSlotAttributes[K] } & { [K in keyof RecipeUiMealSlot & keyof RecipeUiMealSlotAttributes as `prop:${K}`]?: RecipeUiMealSlot[K] };
        "recipe-ui-modal-dialog": Omit<RecipeUiModalDialog, keyof RecipeUiModalDialogAttributes> & { [K in keyof RecipeUiModalDialog & keyof RecipeUiModalDialogAttributes]?: RecipeUiModalDialog[K] } & { [K in keyof RecipeUiModalDialog & keyof RecipeUiModalDialogAttributes as `attr:${K}`]?: RecipeUiModalDialogAttributes[K] } & { [K in keyof RecipeUiModalDialog & keyof RecipeUiModalDialogAttributes as `prop:${K}`]?: RecipeUiModalDialog[K] };
        "recipe-ui-rating-badge": Omit<RecipeUiRatingBadge, keyof RecipeUiRatingBadgeAttributes> & { [K in keyof RecipeUiRatingBadge & keyof RecipeUiRatingBadgeAttributes]?: RecipeUiRatingBadge[K] } & { [K in keyof RecipeUiRatingBadge & keyof RecipeUiRatingBadgeAttributes as `attr:${K}`]?: RecipeUiRatingBadgeAttributes[K] } & { [K in keyof RecipeUiRatingBadge & keyof RecipeUiRatingBadgeAttributes as `prop:${K}`]?: RecipeUiRatingBadge[K] };
        "recipe-ui-search-bar": Omit<RecipeUiSearchBar, keyof RecipeUiSearchBarAttributes> & { [K in keyof RecipeUiSearchBar & keyof RecipeUiSearchBarAttributes]?: RecipeUiSearchBar[K] } & { [K in keyof RecipeUiSearchBar & keyof RecipeUiSearchBarAttributes as `attr:${K}`]?: RecipeUiSearchBarAttributes[K] } & { [K in keyof RecipeUiSearchBar & keyof RecipeUiSearchBarAttributes as `prop:${K}`]?: RecipeUiSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A recipe summary card — used across the discovery grid, favorites list, and
             * the meal-plan recipe picker. Purely presentational: it never fetches data
             * or reads app state, only emits events for the host app to act on.
             */
            "recipe-ui-card": LocalJSX.IntrinsicElements["recipe-ui-card"] & JSXBase.HTMLAttributes<HTMLRecipeUiCardElement>;
            /**
             * A row of toggleable filter chips (e.g. recipe categories or cuisines).
             * Multi-select: clicking a chip emits the full next `selected` array and
             * waits for the host app to feed it back via the `selected` prop — the
             * component does not keep its own copy of selection state.
             */
            "recipe-ui-filter-chip-group": LocalJSX.IntrinsicElements["recipe-ui-filter-chip-group"] & JSXBase.HTMLAttributes<HTMLRecipeUiFilterChipGroupElement>;
            /**
             * Collects a recipe (title, image, category, ingredients, instructions) and
             * emits it on submit. Deliberately has no built-in business validation
             * beyond marking fields as `required` for baseline UX — the host app
             * validates and feeds errors back in via the `errors` prop, per the
             * Recipe Management requirement ("validate recipe input before saving").
             */
            "recipe-ui-form": LocalJSX.IntrinsicElements["recipe-ui-form"] & JSXBase.HTMLAttributes<HTMLRecipeUiFormElement>;
            /**
             * One day's cell in the weekly meal-plan grid: either an "add recipe" prompt or the assigned recipe with a remove control.
             */
            "recipe-ui-meal-slot": LocalJSX.IntrinsicElements["recipe-ui-meal-slot"] & JSXBase.HTMLAttributes<HTMLRecipeUiMealSlotElement>;
            /**
             * A generic modal shell. Used as the meal-plan recipe picker: the host app
             * puts a `<recipe-ui-card>` grid in the default slot and, optionally, action
             * buttons in the `footer` slot.
             */
            "recipe-ui-modal-dialog": LocalJSX.IntrinsicElements["recipe-ui-modal-dialog"] & JSXBase.HTMLAttributes<HTMLRecipeUiModalDialogElement>;
            /**
             * A small colored label — e.g. a difficulty/cuisine/dietary tag on a recipe details page.
             */
            "recipe-ui-rating-badge": LocalJSX.IntrinsicElements["recipe-ui-rating-badge"] & JSXBase.HTMLAttributes<HTMLRecipeUiRatingBadgeElement>;
            /**
             * A debounced search input. Owns only keystroke-to-debounced-event plumbing;
             * it never calls an API itself — the host app listens for `searchChange` and
             * decides what to do with the value.
             */
            "recipe-ui-search-bar": LocalJSX.IntrinsicElements["recipe-ui-search-bar"] & JSXBase.HTMLAttributes<HTMLRecipeUiSearchBarElement>;
        }
    }
}
